export interface IProduct {
  self: {
    href: string
    appLink: string
    enabled: boolean
  }
  priceInfo: {
    priceWithoutVat: string
    priceWithVat: string
    comparePrice: string
    discountRate: string
    pricePrefix: string
    pricePostfix: string
    discountReason: string
    gaPriceWithoutVat: string
    priceNoCurrency: string
    delayedPaymentPriceWithVat: string
  }
  priceInfoV2: {
    priceWithVat: string
    comparePrice: string
    pricePrefix: string
    pricePostfix: string
    priceDescription: string
    priceType: number
    headerText: string
    headerIconUrl: string
    priceSave: string
    explanationPriceAction: string
    unitPriceWithVat: string
    unitName: string
  }
  cpriceTotal: string
  is_comparable: boolean
  priceTotal: string
  promosWorth: string
  ratingCount: number
  specParent: string
  userOwns: boolean
  userOwnedContentId: string
  navigationUrl: string
  canChangeQuantity: boolean
  canCashBack: boolean
  cashBackType: number
  cashBackPriceLabel: string
  cashBackPrice: string
  cashBackPercent: string
  giftAdvisor: string
  catalog_number: string
  count: number
  showUpsellDialog: boolean
  onChangeItemCountClick: string
  icons: Array<{
    text: string
    image: string
    clickAction: string
  }>
  viewerProductInfo: {
    href: string
    appLink: string
    enabled: boolean
  }
  id: number
  code: string
  img: string
  name: string
  spec: string
  price: string
  cprice: string
  priceWithoutVat: string
  avail: string
  avail_postfix: string
  avail_postfix2: string
  availLegend: string
  avail_color: string
  is_action: boolean
  action_name: string
  rating: number
  promo_cnt: number
  promos: string
  order: number
  is_special_service: boolean
  type: number
  year: number
  can_buy: boolean
  itemType: string
  orderItemId: string
  iType: number
  maxCanBuy: number
  eshopType: number
  url: string
  canStream: boolean
  canUserStream: boolean
  supplierCode: string
  parentId: number
  minimumAmount: number
  amountInPack: number
  start_time: string
  end_time: string
  variant_type: number
  priceNoCurrency: string
  categoryName: string
  inBasket: number
}
